import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `wailsjs` is generated by the Wails CLI (and committed), `dist` is build output.
  { ignores: ["dist", "wailsjs", "node_modules", "coverage"] },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      reactHooks.configs.recommended,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      "react-refresh": reactRefresh,
    },
    rules: {
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],

      // `any` is banned rather than merely discouraged: the generated Wails models
      // already type every field the UI reads, so a cast is always a mistake. The
      // rule used to be a warning because the old code was full of
      // `(game as any).platforms` for fields that were plainly declared.
      "@typescript-eslint/no-explicit-any": "error",

      // Unused imports, locals and parameters are errors; the previous codebase
      // shipped dead code precisely because this was off.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],

      // Errors are handled explicitly, never silently swallowed. The one allowed
      // exception is a caught binding that exists only to keep the process moving
      // and is renamed to `_`, which `no-unused-vars` above permits.
      "no-empty": ["error", { allowEmptyCatch: false }],
    },
  },
);
