// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameTag(arg1, arg2) {
  return window['go']['main']['App']['AddGameTag'](arg1, arg2);
}

export function ForceScanGames() {
  return window['go']['main']['App']['ForceScanGames']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetGameCover(arg1) {
  return window['go']['main']['App']['GetGameCover'](arg1);
}

export function GetGameCoverLandscape(arg1) {
  return window['go']['main']['App']['GetGameCoverLandscape'](arg1);
}

export function GetGameList() {
  return window['go']['main']['App']['GetGameList']();
}

export function GetMachineName() {
  return window['go']['main']['App']['GetMachineName']();
}

export function GetQueueInfo() {
  return window['go']['main']['App']['GetQueueInfo']();
}

export function GetSteamUsers() {
  return window['go']['main']['App']['GetSteamUsers']();
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenGameDirectory(arg1) {
  return window['go']['main']['App']['OpenGameDirectory'](arg1);
}

export function OpenGameMetadata(arg1) {
  return window['go']['main']['App']['OpenGameMetadata'](arg1);
}

export function PickGameDirectory() {
  return window['go']['main']['App']['PickGameDirectory']();
}

export function QueueClear() {
  return window['go']['main']['App']['QueueClear']();
}

export function QueuePause() {
  return window['go']['main']['App']['QueuePause']();
}

export function QueueResume() {
  return window['go']['main']['App']['QueueResume']();
}

export function RemoveGameTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveGameTag'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanGames() {
  return window['go']['main']['App']['ScanGames']();
}

export function ScrapeAllGames() {
  return window['go']['main']['App']['ScrapeAllGames']();
}

export function ScrapeGame(arg1) {
  return window['go']['main']['App']['ScrapeGame'](arg1);
}

export function SetPreferredSource(arg1, arg2) {
  return window['go']['main']['App']['SetPreferredSource'](arg1, arg2);
}

export function SetPrimaryExecutable(arg1, arg2) {
  return window['go']['main']['App']['SetPrimaryExecutable'](arg1, arg2);
}

export function SetSteamUser(arg1) {
  return window['go']['main']['App']['SetSteamUser'](arg1);
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function ToggleGameStar(arg1) {
  return window['go']['main']['App']['ToggleGameStar'](arg1);
}

export function UpdateGameInfo(arg1) {
  return window['go']['main']['App']['UpdateGameInfo'](arg1);
}
