// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppInfo():Promise<Record<string, string>>;

export function GetConfig():Promise<main.Config>;

export function GetGame(arg1:string):Promise<main.GameInfo>;

export function GetGameList():Promise<Array<main.GameInfo>>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function ScanGames():Promise<Array<main.ScanResult>>;

export function UpdateGameInfo(arg1:main.GameInfo):Promise<void>;
