// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {main} from '../models';
import {config} from '../models';
import {game} from '../models';
import {taskqueue} from '../models';

export function AddGameTag(arg1:string,arg2:string):Promise<void>;

export function CommonPaths():Promise<Record<string, string>>;

export function ForceScanGames():Promise<Array<scanner.ScanResult>>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetConfig():Promise<config.Config>;

export function GetGame(arg1:string):Promise<game.GameInfo>;

export function GetGameList():Promise<Array<game.GameInfo>>;

export function GetGamePathLabels():Promise<Record<string, Array<string>>>;

export function GetMachineName():Promise<string>;

export function GetQueueInfo():Promise<taskqueue.Status>;

export function GetSteamPath():Promise<string>;

export function GetSteamUsers():Promise<Array<main.SteamUserInfo>>;

export function LaunchGame(arg1:string):Promise<void>;

export function OpenBrowser(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenGameDirectory(arg1:string):Promise<void>;

export function OpenGameMetadata(arg1:string):Promise<void>;

export function PickGameDirectory():Promise<string>;

export function QueueClear():Promise<void>;

export function QueuePause():Promise<void>;

export function QueueResetProgress():Promise<void>;

export function QueueResume():Promise<void>;

export function QueueScrapeAll(arg1:boolean):Promise<number>;

export function QueueSetConcurrency(arg1:number):Promise<void>;

export function RemoveGameTag(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanGames():Promise<Array<scanner.ScanResult>>;

export function ScrapeGame(arg1:string):Promise<main.ScrapeReport>;

export function SetPreferredSource(arg1:string,arg2:string):Promise<void>;

export function SetPrimaryExecutable(arg1:string,arg2:string):Promise<void>;

export function SetSteamUser(arg1:string):Promise<void>;

export function ToggleGameStar(arg1:string):Promise<void>;
