// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {game} from '../models';
import {scanner} from '../models';

export function GetAppInfo():Promise<Record<string, string>>;

export function GetConfig():Promise<config.Config>;

export function GetGame(arg1:string):Promise<game.GameInfo>;

export function GetGameList():Promise<Array<game.GameInfo>>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanGames():Promise<Array<scanner.ScanResult>>;

export function UpdateGameInfo(arg1:game.GameInfo):Promise<void>;
